kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: USER
      password:
        from_secret: DOCKER_PASSWORD
      repo: USER/template-express-ts
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: deploy
    image: k3env/nomad
    environment:
      NOMAD_ADDR:
        from_secret: NOMAD_ADDR
      NOMAD_TOKEN:
        from_secret: NOMAD_TOKEN
      NOMAD_VAR_service_tag: ${DRONE_COMMIT_SHA:0:8}
    commands:
      - 'nomad job run deploy/jobspec.nomad'
